name: "ml_canzian"

feature_definition:
  use_norm_features: False # whether to use normalized features
  empty_feature_filtering_th: 0.9 # remove features based on a threshold
  include_device_type: False # whether to include device type in the feature matrix # whether to include device type in the feature matrix
  # Feature used in the paper (a subset that is compatible within the dataset)
  feature_list: [
            "f_loc:phone_locations_barnett_disttravelled:14dhist",
            "f_loc:phone_locations_barnett_maxdiam:14dhist",
            "f_loc:phone_locations_barnett_rog:14dhist",
            "f_loc:phone_locations_barnett_stdflightlen:14dhist",
            "f_loc:phone_locations_barnett_maxhomedist:14dhist",
            "f_loc:phone_locations_doryab_numberofsignificantplaces:14dhist",
            "f_loc:phone_locations_barnett_circdnrtn:14dhist",
        ]

training_params:
  verbose: 0
  # whether to save and re-use features repetitively
  #     True only when re-running the exact same model training
  save_and_reload: False