name: "ml_wahle"

feature_definition:
  use_norm_features: False # whether to use normalized features
  empty_feature_filtering_th: 0.9 # remove features based on a threshold
  include_device_type: False # whether to include device type in the feature matrix
  # Feature used in the paper (a subset that is compatible within the dataset)
  feature_list_base: [
            "f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout",
            "f_loc:phone_locations_barnett_hometime",
            "f_loc:phone_locations_barnett_maxdiam",
            "f_loc:phone_locations_barnett_disttravelled",
            "f_loc:phone_locations_doryab_loglocationvariance",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            # not available for all datasets
            # "f_wifi:phone_wifi_connected_rapids_uniquedevices",
            # "f_call:phone_calls_rapids_incoming_count",
            # "f_call:phone_calls_rapids_outgoing_count",
        ]

training_params:
  verbose: 0
  # whether to save and re-use features repetitively
  #     True only when re-running the exact same model training
  save_and_reload: False
